sudo: required
language: ruby
rvm:
  - 2.6.0
services:
  - docker
before_install:
  - docker pull yegor256/papers
script:
  - docker run -v "$(pwd)":/repo yegor256/papers /bin/bash -c "cd /repo; bundle update; bundle exec rake --quiet"

